//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaServicios.Servicios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ArchivoDeRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ArchivoDeRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaServicios.Servicios.ArchivoDeRecursos", typeof(ArchivoDeRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BotonBuscar {
            get {
                return ResourceManager.GetString("BotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BotonCancelar {
            get {
                return ResourceManager.GetString("BotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar.
        /// </summary>
        public static string BotonCargar {
            get {
                return ResourceManager.GetString("BotonCargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string BotonCerrar {
            get {
                return ResourceManager.GetString("BotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string BotonEnviar {
            get {
                return ResourceManager.GetString("BotonEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a Excel.
        /// </summary>
        public static string BotonExportarExcel {
            get {
                return ResourceManager.GetString("BotonExportarExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar.
        /// </summary>
        public static string BotonFinalizar {
            get {
                return ResourceManager.GetString("BotonFinalizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string BotonGuardar {
            get {
                return ResourceManager.GetString("BotonGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar y enviar.
        /// </summary>
        public static string BotonGuardarEnviar {
            get {
                return ResourceManager.GetString("BotonGuardarEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Herramientas de búsqueda.
        /// </summary>
        public static string BotonHerramientasBusqueda {
            get {
                return ResourceManager.GetString("BotonHerramientasBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string BotonIniciarSesion {
            get {
                return ResourceManager.GetString("BotonIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar todos.
        /// </summary>
        public static string BotonMostrarTodos {
            get {
                return ResourceManager.GetString("BotonMostrarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Escenario.
        /// </summary>
        public static string BotonNuevoEscenario {
            get {
                return ResourceManager.GetString("BotonNuevoEscenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo registro.
        /// </summary>
        public static string BotonNuevoRegistro {
            get {
                return ResourceManager.GetString("BotonNuevoRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        public static string BotonRegresar {
            get {
                return ResourceManager.GetString("BotonRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver a la lista.
        /// </summary>
        public static string BotonRegresarALaLista {
            get {
                return ResourceManager.GetString("BotonRegresarALaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requisitos.
        /// </summary>
        public static string BotonRequisitos {
            get {
                return ResourceManager.GetString("BotonRequisitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string BotonSeleccionar {
            get {
                return ResourceManager.GetString("BotonSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        public static string BotonSiguiente {
            get {
                return ResourceManager.GetString("BotonSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Escenario Cultural.
        /// </summary>
        public static string BotonTeatro {
            get {
                return ResourceManager.GetString("BotonTeatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para registrarse es necesario haya leído y este de acuerdo con los términos y condiciones..
        /// </summary>
        public static string Mensaje_AutorizacionRegistro {
            get {
                return ResourceManager.GetString("Mensaje_AutorizacionRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los cambios fueron guardados exitosamente..
        /// </summary>
        public static string Mensaje_CambiosGuardadosExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_CambiosGuardadosExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de certificado se encuentra en Revisión..
        /// </summary>
        public static string Mensaje_CertificadoContribucionEnRevision {
            get {
                return ResourceManager.GetString("Mensaje_CertificadoContribucionEnRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El certificado tributario no puede ser generado. Productor no lo ha solicitado o está en revisión..
        /// </summary>
        public static string Mensaje_CertificadoTributarioPendiente {
            get {
                return ResourceManager.GetString("Mensaje_CertificadoTributarioPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Concepto fue guardado exitosamente.
        /// </summary>
        public static string Mensaje_ConceptoGuardadoExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_ConceptoGuardadoExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El descuento ha sido guardado exitosamnete.
        /// </summary>
        public static string Mensaje_DescuentoGuardado {
            get {
                return ResourceManager.GetString("Mensaje_DescuentoGuardado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario o la contraseña introducidos no son correctos..
        /// </summary>
        public static string Mensaje_ErrorAutenticacion {
            get {
                return ResourceManager.GetString("Mensaje_ErrorAutenticacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico {0} no se encuentra registrado..
        /// </summary>
        public static string Mensaje_ErrorCorreoNoRegistrado {
            get {
                return ResourceManager.GetString("Mensaje_ErrorCorreoNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presentó error enviando correo electrónico.
        /// </summary>
        public static string Mensaje_ErrorEnviandoCorreo {
            get {
                return ResourceManager.GetString("Mensaje_ErrorEnviandoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, el perfil de usuario al que usted pertenece se encuentra inactivo..
        /// </summary>
        public static string Mensaje_ErrorPerfilInactivo {
            get {
                return ResourceManager.GetString("Mensaje_ErrorPerfilInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, su cuenta de usuario se encuentra inactiva..
        /// </summary>
        public static string Mensaje_ErrorUsuarioInactivo {
            get {
                return ResourceManager.GetString("Mensaje_ErrorUsuarioInactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El evento no se encuentra en la lista.
        /// </summary>
        public static string Mensaje_EventoNoSeEncuentraLista {
            get {
                return ResourceManager.GetString("Mensaje_EventoNoSeEncuentraLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --- El operador no se encuentra en la lista ---.
        /// </summary>
        public static string Mensaje_OperadorNoSeEncuentraLista {
            get {
                return ResourceManager.GetString("Mensaje_OperadorNoSeEncuentraLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro escenario.
        /// </summary>
        public static string Mensaje_OtroEscenario {
            get {
                return ResourceManager.GetString("Mensaje_OtroEscenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --- El productor no se encuentra en la lista ---.
        /// </summary>
        public static string Mensaje_ProductorNoSeEncuentraLista {
            get {
                return ResourceManager.GetString("Mensaje_ProductorNoSeEncuentraLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productor en revisión o en proceso de aprobación. No puede obtener certificado ni registrar eventos..
        /// </summary>
        public static string Mensaje_ProductorSinCodigo {
            get {
                return ResourceManager.GetString("Mensaje_ProductorSinCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un productor registrado con ese número de identificación..
        /// </summary>
        public static string Mensaje_ProductorYaExiste {
            get {
                return ResourceManager.GetString("Mensaje_ProductorYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue eliminado exitosamente..
        /// </summary>
        public static string Mensaje_RegistroEliminadoExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_RegistroEliminadoExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique que el productor tenga los requisitos completos. No puede ser generado código de productor..
        /// </summary>
        public static string Mensaje_RequisitosIncompletos {
            get {
                return ResourceManager.GetString("Mensaje_RequisitosIncompletos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione....
        /// </summary>
        public static string Mensaje_SeleccioneUnaOpcion {
            get {
                return ResourceManager.GetString("Mensaje_SeleccioneUnaOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta ingresar el tipo de certificado..
        /// </summary>
        public static string Mensaje_SinRevisionCertificado {
            get {
                return ResourceManager.GetString("Mensaje_SinRevisionCertificado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Solicitud de autorización cambio de estado y fue notificado exitosamente.
        /// </summary>
        public static string Mensaje_SolicitudCambioEstadoNotificacionExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_SolicitudCambioEstadoNotificacionExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presenta una solicitud asociada al Solicitante.
        /// </summary>
        public static string Mensaje_SolicitudEnviada {
            get {
                return ResourceManager.GetString("Mensaje_SolicitudEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Solicitud fue enviada exitosamente.
        /// </summary>
        public static string Mensaje_SolicitudEnviadaExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_SolicitudEnviadaExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Solicitud fue guardada exitosamente.
        /// </summary>
        public static string Mensaje_SolicitudGuardadaExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_SolicitudGuardadaExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Solicitud fue Modificada exitosamente; pero el resultado no fué asignado por falta de conceptos.
        /// </summary>
        public static string Mensaje_SolicitudModificadaExitosamente {
            get {
                return ResourceManager.GetString("Mensaje_SolicitudModificadaExitosamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EventoEncontrado.
        /// </summary>
        public static string Valor_EventoEncontrado {
            get {
                return ResourceManager.GetString("Valor_EventoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EventoEncontradoOtroMunicipio.
        /// </summary>
        public static string Valor_EventoEncontradoOtroMunicipio {
            get {
                return ResourceManager.GetString("Valor_EventoEncontradoOtroMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EventoNoEncontrado.
        /// </summary>
        public static string Valor_EventoNoEncontrado {
            get {
                return ResourceManager.GetString("Valor_EventoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evento no registrado.
        /// </summary>
        public static string Valor_EventoNoRegistrado {
            get {
                return ResourceManager.GetString("Valor_EventoNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operador no registrado.
        /// </summary>
        public static string Valor_OperadorNoRegistrado {
            get {
                return ResourceManager.GetString("Valor_OperadorNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Productor no registrado.
        /// </summary>
        public static string Valor_ProductorNoRegistrado {
            get {
                return ResourceManager.GetString("Valor_ProductorNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HttpPostedFileBase, ObjectState, ICollection`1, List`1, Byte[].
        /// </summary>
        public static string Valor_TiposDeDatosExcluir {
            get {
                return ResourceManager.GetString("Valor_TiposDeDatosExcluir", resourceCulture);
            }
        }
    }
}
