
var Alto = [
    { 'codMunicipio': '19050', 'Municipio': 'Argelia' },
    { 'codMunicipio': '19075', 'Municipio': 'Balboa' },
    { 'codMunicipio': '19110', 'Municipio': 'Buenos Aires' },
    { 'codMunicipio': '19130', 'Municipio': 'Cajibío' },
    { 'codMunicipio': '19137', 'Municipio': 'Caldono' },
    { 'codMunicipio': '19142', 'Municipio': 'Caloto' },
    { 'codMunicipio': '19212', 'Municipio': 'Corinto' },
    { 'codMunicipio': '52233', 'Municipio': 'Cumbitara' },
    { 'codMunicipio': '52256', 'Municipio': 'El Rosario' },
    { 'codMunicipio': '19256', 'Municipio': 'El Tambo' },
    { 'codMunicipio': '76275', 'Municipio': 'Florida' },
    { 'codMunicipio': '19364', 'Municipio': 'Jambaló' },
    { 'codMunicipio': '52405', 'Municipio': 'Leiva' },
    { 'codMunicipio': '52418', 'Municipio': 'Los Andes' },
    { 'codMunicipio': '19450', 'Municipio': 'Mercaderes' },
    { 'codMunicipio': '19455', 'Municipio': 'Miranda' },
    { 'codMunicipio': '19473', 'Municipio': 'Morales' },
    { 'codMunicipio': '19532', 'Municipio': 'Patía' },
    { 'codMunicipio': '19548', 'Municipio': 'Piendamó' },
    { 'codMunicipio': '52540', 'Municipio': 'Policarpa' },
    { 'codMunicipio': '76563', 'Municipio': 'Pradera' },
    { 'codMunicipio': '19698', 'Municipio': 'Santander de Quilichao' },
    { 'codMunicipio': '19780', 'Municipio': 'Suárez' },
    { 'codMunicipio': '19821', 'Municipio': 'Toribío' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },


];


var Antioquia = [
{ 'codMunicipio': '05031', 'Municipio': 'Amalfi' },
{ 'codMunicipio': '05040', 'Municipio': 'Anorí' },
{ 'codMunicipio': '05107', 'Municipio': 'Briceño' },
{ 'codMunicipio': '05154', 'Municipio': 'Caucasia' },
{ 'codMunicipio': '05250', 'Municipio': 'El Bagre' },
{ 'codMunicipio': '05361', 'Municipio': 'Ituango' },
{ 'codMunicipio': '05495', 'Municipio': 'Nechí' },
{ 'codMunicipio': '05604', 'Municipio': 'Remedios' },
{ 'codMunicipio': '05736', 'Municipio': 'Segovia' },
{ 'codMunicipio': '05790', 'Municipio': 'Tarazá' },
{ 'codMunicipio': '05854', 'Municipio': 'Valdivia' },
{ 'codMunicipio': '05895', 'Municipio': 'Zaragoza' },
{ 'codMunicipio': '', 'Municipio': '' },
{ 'codMunicipio': '', 'Municipio': '' },
{ 'codMunicipio': '', 'Municipio': '' },
];
var Catatumbo = [
{ 'codMunicipio': '54206', 'Municipio': 'Convención' },
{ 'codMunicipio': '54245', 'Municipio': 'El Carmen' },
{ 'codMunicipio': '54250', 'Municipio': 'El Tarra' },
{ 'codMunicipio': '54344', 'Municipio': 'Hacarí' },
{ 'codMunicipio': '54670', 'Municipio': 'San Calixto' },
{ 'codMunicipio': '54720', 'Municipio': 'Sardinata' },
{ 'codMunicipio': '54800', 'Municipio': 'Teorama' },
{ 'codMunicipio': '54810', 'Municipio': 'Tibú' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },
];

var Pacifico = [
    { 'codMunicipio': '52079', 'Municipio': 'Barbacoas' },
    { 'codMunicipio': '52250', 'Municipio': 'El Charco' },
    { 'codMunicipio': '52520', 'Municipio': 'Francisco Pizarro' },
    { 'codMunicipio': '52390', 'Municipio': 'La Tola' },
    { 'codMunicipio': '52427', 'Municipio': 'Magüi' },
    { 'codMunicipio': '52473', 'Municipio': 'Mosquera' },
    { 'codMunicipio': '52490', 'Municipio': 'Olaya Herrera' },
    { 'codMunicipio': '52612', 'Municipio': 'Ricaurte' },
    { 'codMunicipio': '52621', 'Municipio': 'Roberto Payán' },
    { 'codMunicipio': '52835', 'Municipio': 'San Andrés de Tumaco' },
    { 'codMunicipio': '52696', 'Municipio': 'Santa Bárbara' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },
    
];
var Sierra = [
    { 'codMunicipio': '20013', 'Municipio': 'Agustín Codazzi' },
    { 'codMunicipio': '47053', 'Municipio': 'Aracataca' },
    { 'codMunicipio': '20045', 'Municipio': 'Becerril' },
    { 'codMunicipio': '47189', 'Municipio': 'Ciénaga' },
    { 'codMunicipio': '44090', 'Municipio': 'Dibulla' },
    { 'codMunicipio': '44279', 'Municipio': 'Fonseca' },
    { 'codMunicipio': '47288', 'Municipio': 'Fundación' },
    { 'codMunicipio': '20400', 'Municipio': 'La Jagua de Ibirico' },
    { 'codMunicipio': '20621', 'Municipio': 'La Paz' },
    { 'codMunicipio': '20443', 'Municipio': 'Manaure' },
    { 'codMunicipio': '20570', 'Municipio': 'Pueblo Bello' },
    { 'codMunicipio': '20750', 'Municipio': 'San Diego' },
    { 'codMunicipio': '44650', 'Municipio': 'San Juan del Cesar' },
    { 'codMunicipio': '47001', 'Municipio': 'Santa Marta' },
    { 'codMunicipio': '20001', 'Municipio': 'Valledupar' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },
    { 'codMunicipio': '', 'Municipio': '' },

];
